version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pogrebok_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2441
      POSTGRES_DB: pogrebok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  app:
    build: .
    container_name: pogrebok_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 2441
      DB_NAME: pogrebok

volumes:
  postgres_data: